version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: wb-api
    container_name: wb-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    working_dir: /var/www/html/wirelessbackup-api/
    volumes:
      - .:/var/www/html/wirelessbackup-api
    networks:
      - app-network

#Nginx Service
  webserver:
    image: nginx:1.16-alpine
    container_name: wb-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/wirelessbackup-api
      - ./sourcefiles/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16